version: "3"
services:
  nginx:
    image: nginx:stable-alpine

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Cardekho123
    volumes:
      - mongo-db:/data/db # Named volume

  redis:
    image: redis

# List of all NAMED volumes
volumes:
  mongo-db: