version: "3"
services:
  node-app:
    build: .  # path to Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app # bind mount
      - /app/node_modules # anonymous volume
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env