version: "3"
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # Passing nginx config using bind mount

  node-app:
    deploy:
      replicas: 8
      restart-policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: . # Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}  # Env variables from Vm on which this docker will run.
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_IP=${MONGO_IP}
      - MONGO_PORT=${MONGO_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}